[project]
name = "adam_impact_study"
version = "0.1.0"
description = ""
authors = [
    {name = "Kathleen Kiker", email = "kathleen@b612foundation.orgm"},
]
dependencies = [
    "matplotlib",
    "adam_core>=0.3.4",
    "adam_assist>=0.2.0",
    "sorcha",
]
requires-python = "<3.13,>=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.optional-dependencies]
dev = [
    "black",
    "ipython",
    "isort",
    "mypy",
    "pdm",
    "pytest-benchmark",
    "pytest-cov",
    "pytest-doctestplus",
    "pytest-mock",
    "pytest",
    "ruff",
    "adam-assist @ git+https://github.com/B612-Asteroid-Institute/adam-assist.git@9ddc2c3b4c99d35e0f29a7cd2f77dce05d3efa76",
]

[tool.pdm.scripts]
check = { composite = ["lint", "typecheck", "test"] }
format = { composite = ["black ./src/adam_impact_study", "isort ./src/adam_impact_study"] }
lint = { composite = [
  "ruff check ./src/adam_impact_study",
  "black --check ./src/adam_impact_study",
  "isort --check-only ./src/adam_impact_study",
] }
fix = "ruff ./src/adam_impact_study --fix"
typecheck = "mypy --strict ./src/adam_impact_study"

test = "pytest --benchmark-disable {args}"
doctest = "pytest --doctest-plus --doctest-only"
benchmark = "pytest --benchmark-only"
coverage = "pytest --cov=adam_impact_study --cov-report=xml"

[tool.pdm]
distribution = true
# We use our fork but sorcha wants to install vanilla assist
resolution.excludes = ["assist"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 110
target-version = "py311"
lint.ignore = []
exclude = ["build"]
