[project]
name = "adam_impact_study"
version = "0.1.0"
description = ""
authors = [
    {name = "Kathleen Kiker", email = "kathleen@b612foundation.orgm"},
]
dependencies = [
    "numpy",
    "matplotlib",
    "adam_core @ git+https://github.com/B612-Asteroid-Institute/adam_core.git@13165ed9feedb8d2e06e39f95a90ed61fd0a8b0e",
    "sorcha",
    "jax==0.4.17",
    "jaxlib==0.4.17",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.optional-dependencies]
dev = [
  "black",
  "ipython",
  "isort",
  "mypy",
  "pdm",
  "pytest-benchmark",
  "pytest-cov",
  "pytest-doctestplus",
  "pytest-mock",
  "pytest",
  "ruff",
]

[tool.pdm]
distribution = true

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
